### PR TITLE
Update pl branch with textmate/master

### PR DESCRIPTION
**Pull request by adaedra**
This is a simple pull of `textmate/master` into the `pl` branch with merge to make it work.

Since `aroben/pl` is currently the selected syntax file for GitHub code highlighting, this should pull the last improvements from upstream to here, e.g. the fix for 2.3's `<<~HEREDOC`.

I don't know if this is the correct course of action or if this repository is even maintained. Please redirect me to the correct procedure if necessary (My first action would have been to make `textmate/master` the selected syntax, but it apparently lacks the fix for GraphQL syntax and it maybe important for GitHub.)

I tried the syntax with Lightshow and it works correctly: [See here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fadaedra%2Fruby.tmbundle%2Fpl%2FSyntaxes%2FRuby.plist&grammar_text=&code_source=from-text&code_url=&code=foo+%3C%3C-EOF%0D%0AHello+%27+world%0D%0AEOF%0D%0A%0D%0Abar+%3C%3C%7EEOF%0D%0AHello+%27+world%0D%0AEOF%0D%0A%0D%0Adef+foo%0D%0A++%27hello%27%0D%0Aend%0D%0A%0D%0Ahello+%3C%3C-GRAPHQL%0D%0A%7B%0D%0A++me+%7B%0D%0A++++name%0D%0A++%7D%0D%0A%7D%0D%0AEND%0D%0A%0D%0A).

### CODE REVIEW

**Comment by adaedra** [comment]
Hello, is this repository maintained anymore? @aroben ?

**Comment by aroben** [comment]
Sorry for the slow response, it was a holiday weekend here and I was busy with family.

It looks like this PR is against the `master` branch, but it should probably be against the `pl` branch instead since that's what Linguist uses.

This repository has never been particularly well maintained, and even less so now that I no longer work at GitHub. If you'd like to maintain the Ruby highlighting it might make sense for you to create your own fork and open a PR on Linguist to switch to your fork. Or maybe @lildude or someone else from GitHub would like to create a fork?

**Comment by adaedra** [comment]
Ah, error from me on the base branch. This is fixed (in case this PR goes anywhere).

I created my fork mainly to make the merge which couldn't be done automatically. If this repository is not meant to continue, I would suggest linguist would move back to textmate repository, backporting the differences between this repository and its parent if needed, which would remove the need for a separate fork.

I am not sure about the next steps on this. Is this something that should be discussed on github/linguist instead?

**Comment by aroben** [comment]
Getting the changes upstreamed into textmate/ruby.tmbundle seems ideal. I tried to do that in https://github.com/textmate/ruby.tmbundle/pull/73 but it's been stalled for a long time. Pinging that PR and/or opening an issue on github/linguist seem like good ways to go.

**Comment by adaedra** [comment]
I see three commits in pl that would have to be upstreamed:

1. Cancelling the different priority for '/='
2. Fixing the heredocs in argument lists
3. Allowing GraphQL heredocs

Change 2 is addressed in your PR which is indeed stalled (and nothing has been done since), and change 3 has never been upstreamed (I see that it was proposed on #1 but never addressed). For change 1, I have no idea if it is still applicable.

I'll open an issue on linguist to at least have their opinion on the matter and maybe track the issue there. Thank you for your replies.

**Comment by adaedra** [comment]
Since github/linguist#3782 has been merged, this can be closed.

**Pull request closed without merging**
